name: gk_shoecare_admin
description: App admin GK Shoecare - lihat pesanan masuk
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/iconadmin.png"

flutter:
  uses-material-design: true
